export const MOVIES_LIST_SUCCESS = 'MOVIES_LIST_SUCCESS';
export const MOVIES_LIST_ERROR = 'MOVIES_LIST_ERROR';
export const MOVIES_LIST_LOADING = 'MOVIES_LIST_LOADING';
export const CLEAR_MOVIES_API_STATE = 'CLEAR_MOVIES_API_STATE';
export const ADD_SHORT_LIST_MOVIE = 'ADD_SHORT_LIST_MOVIE';
